# Generated by Django 4.1.5 on 2023-08-06 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_alter_game_price_alter_game_size'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mistuser',
            name='library',
            field=models.ManyToManyField(blank=True, related_name='users_library', to='games.game'),
        ),
    ]
