# Generated by Django 4.1.5 on 2023-07-31 06:10

import Mist2.games.validators
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2)])),
                ('genre', models.CharField(blank=True, choices=[('ACTION', 'Action'), ('PUZZLE', 'Puzzle'), ('HORROR', 'Horror'), ('STRATEGY', 'Strategy'), ('PLATFORMER', 'Platformer')], max_length=10, null=True)),
                ('release_date', models.DateTimeField(auto_now_add=True)),
                ('game_photo', models.ImageField(blank=True, null=True, upload_to='images', validators=[Mist2.games.validators.image_size_validator_5mb])),
                ('size', models.PositiveIntegerField()),
                ('price', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True, max_length=300, null=True, validators=[django.core.validators.MinLengthValidator(10)])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
