# Generated by Django 4.1.5 on 2023-07-27 07:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_alter_game_game_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='price',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxValueValidator(60)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='size',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxValueValidator(128)]),
            preserve_default=False,
        ),
    ]
